name : CI

on : 
  schedule :
  - cron : '0/5 * * * *'

  workflow_dispatch:

jobs:
  build:

    runs-on : ubuntu-latest

    steps:
    - uses : actions/checkout@v3

    - name: Run script
      run:
        echo "  " >> Readme.md
        git config user.name "kristowb"
        git config user.email "humangreed48@gmail.com"
        git add Readme.md
        git commit -m "Always green!"
        git push